import '/flutter_flow/flutter_flow_icon_button.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/widgets/index.dart' as custom_widgets;
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';

class PopupLanguesModel extends FlutterFlowModel {
  /// Initialization and disposal methods.

  void initState(BuildContext context) {}

  void dispose() {}

  /// Additional helper methods are added here.

  selectLang() {
    List<String> listLang = [
      "Afrikaans",
      "Albanais",
      "Allemand",
      "Amharique",
      "Anglais",
      "Arabe",
      "Arménien",
      "Azéri",
      "Basque",
      "Bengali",
      "Biélorusse",
      "Birman",
      "Bosniaque",
      "Bulgare",
      "Catalan",
      "Cebuano",
      "Chichewa",
      "Chinois (simplifié)",
      "Chinois (traditionnel)",
      "Cingalais",
      "Coréen",
      "Corse",
      "Créole haïtien",
      "Croate",
      "Danois",
      "Espagnol",
      "Espéranto",
      "Estonien",
      "Finnois",
      "Français",
      "Frison",
      "Gaélique écossais",
      "Galicien",
      "Gallois",
      "Géorgien",
      "Grec",
      "Gujarati",
      "Haoussa",
      "Hawaïen",
      "Hébreu",
      "Hindi",
      "Hmong",
      "Hongrois",
      "Igbo",
      "Indonésien",
      "Irlandais",
      "Islandais",
      "Italien",
      "Japonais",
      "Javanais",
      "Kannada",
      "Kazakh",
      "Khmer",
      "Kirghize",
      "Kirundi",
      "Kinyarwanda",
      "Kurde",
      "Laotien",
      "Latin",
      "Letton",
      "Lituanien",
      "Luxembourgeois",
      "Macédonien",
      "Malais",
      "Malayalam",
      "Malgache",
      "Maltais",
      "Maori",
      "Marathi",
      "Mongol",
      "Néerlandais",
      "Népalais",
      "Norvégien",
      "Ouzbek",
      "Pachtô",
      "Panjabi",
      "Persan",
      "Polonais",
      "Portugais",
      "Roumain",
      "Russe",
      "Samoan",
      "Serbe",
      "Sesotho",
      "Shona",
      "Sindhi",
      "Slovaque",
      "Slovène",
      "Somali",
      "Sotho du Sud",
      "Soundanais",
      "Suédois",
      "Swahili",
      "Tadjik",
      "Tagalog",
      "Tamoul",
      "Tchèque",
      "Telugu",
      "Thaï",
      "Turc",
      "Ukrainien",
      "Urdu",
      "Vietnamien",
      "Xhosa",
      "Yiddish",
      "Yorouba",
      "Zoulou"
    ];

    return listLang;
  }
}
